### ISSUE TITLE
Remove-sbRDSession console waits for each session to log off

### ISSUE THREAD

**Issue by steevaavoo** [steevaavoo/ManageRDSessions#4]
Find a way to run them in parallel and report results of all afterwards if possible.

**Comment by adamrushuk** [comment]
A solution to this could be using jobs, eg: `Start-Job` 
Also could look at `Invoke-Parallel`: https://github.com/RamblingCookieMonster/Invoke-Parallel

**Comment by steevaavoo** [comment]
Consider using this: (thanks to @adamrushuk for the suggestion)

```
$jobs = Start-Job -ScriptBlock $sb
$jobs | Wait-Job -Verbose
```

**Comment by steevaavoo** [comment]
Added a modified version of this, with -AsJob switch, to allow user to choose whether to wait for each logoff, or to submit all to Job function. Works great! Thanks again, @adamrushuk :)

**Comment by adamrushuk** [comment]
Happy to help! :)
